(test
 (name dartea_test)
 (deps
  dartea_runtime_test.c
  (source_tree errors)
  (source_tree emitted)
  (source_tree upstream)
  (source_tree ../playgrounds)
  ../bin/main.exe
  ../lib/codegen/c/dartea_runtime.h
  (source_tree ../lib))
 (libraries
  dartea
  typed
  parse
  ast
  data
  ounit2
  qcheck-core
  qcheck-ounit
  unix
  str
  after_typed
  optimized
  infer
  canonicalization
  interface
  ir
  project
  diagnostic
  packages
  registry
  tar
  tar.gz
  tar-unix
  decompress.gz
  digestif
  base64
  codegen_js))
