(test
 (name dartea_test)
 (deps
  dartea_runtime_test.c
  (source_tree errors)
  ../lib/codegen/c/dartea_runtime.h
  (source_tree ../lib))
 (libraries
  dartea
  typed
  parse
  ast
  data
  ounit2
  qcheck-core
  qcheck-ounit
  unix
  after_typed
  optimized
  infer
  canonicalization
  interface
  ir
  file_loader
  codegen_js))
