(rule
 (target prelude_source.ml)
 (deps
  packages/core/Basics.elm
  packages/browser/Browser.elm
  packages/browser/Browser.Dom.elm
  packages/browser/Browser.Events.elm
  packages/browser/Browser.Navigation.elm
  packages/url/Url.elm
  packages/url/Url.Builder.elm
  packages/url/Url.Parser.elm
  packages/url/Url.Parser.Internal.elm
  packages/url/Url.Parser.Query.elm
  packages/core/Char.elm
  packages/core/Dict.elm
  packages/html/Html.elm
  packages/html/Html.Attributes.elm
  packages/html/Html.Events.elm
  packages/html/Html.Keyed.elm
  packages/html/Html.Lazy.elm
  packages/http/Http.elm
  packages/json/Json.Decode.elm
  packages/json/Json.Encode.elm
  packages/core/List.elm
  packages/core/Maybe.elm
  packages/core/Platform.elm
  packages/core/Platform.Cmd.elm
  packages/core/Platform.Sub.elm
  packages/core/Result.elm
  packages/core/String.elm
  packages/core/Task.elm
  packages/time/Time.elm
  packages/core/Tuple.elm
  packages/virtual-dom/VirtualDom.elm)
 (action
  (with-stdout-to
   prelude_source.ml
   (progn
    (echo "let basics = {elm|")
    (cat packages/core/Basics.elm)
    (echo "|elm}\n\nlet browser = {elm|")
    (cat packages/browser/Browser.elm)
    (echo "|elm}\n\nlet char = {elm|")
    (cat packages/core/Char.elm)
    (echo "|elm}\n\nlet dict = {elm|")
    (cat packages/core/Dict.elm)
    (echo "|elm}\n\nlet html = {elm|")
    (cat packages/html/Html.elm)
    (echo "|elm}\n\nlet html_attributes = {elm|")
    (cat packages/html/Html.Attributes.elm)
    (echo "|elm}\n\nlet html_events = {elm|")
    (cat packages/html/Html.Events.elm)
    (echo "|elm}\n\nlet html_keyed = {elm|")
    (cat packages/html/Html.Keyed.elm)
    (echo "|elm}\n\nlet html_lazy = {elm|")
    (cat packages/html/Html.Lazy.elm)
    (echo "|elm}\n\nlet http = {elm|")
    (cat packages/http/Http.elm)
    (echo "|elm}\n\nlet json_decode = {elm|")
    (cat packages/json/Json.Decode.elm)
    (echo "|elm}\n\nlet json_encode = {elm|")
    (cat packages/json/Json.Encode.elm)
    (echo "|elm}\n\nlet list = {elm|")
    (cat packages/core/List.elm)
    (echo "|elm}\n\nlet maybe = {elm|")
    (cat packages/core/Maybe.elm)
    (echo "|elm}\n\nlet platform = {elm|")
    (cat packages/core/Platform.elm)
    (echo "|elm}\n\nlet platform_cmd = {elm|")
    (cat packages/core/Platform.Cmd.elm)
    (echo "|elm}\n\nlet platform_sub = {elm|")
    (cat packages/core/Platform.Sub.elm)
    (echo "|elm}\n\nlet result = {elm|")
    (cat packages/core/Result.elm)
    (echo "|elm}\n\nlet string = {elm|")
    (cat packages/core/String.elm)
    (echo "|elm}\n\nlet task = {elm|")
    (cat packages/core/Task.elm)
    (echo "|elm}\n\nlet time = {elm|")
    (cat packages/time/Time.elm)
    (echo "|elm}\n\nlet browser_dom = {elm|")
    (cat packages/browser/Browser.Dom.elm)
    (echo "|elm}\n\nlet browser_events = {elm|")
    (cat packages/browser/Browser.Events.elm)
    (echo "|elm}\n\nlet browser_navigation = {elm|")
    (cat packages/browser/Browser.Navigation.elm)
    (echo "|elm}\n\nlet url = {elm|")
    (cat packages/url/Url.elm)
    (echo "|elm}\n\nlet url_builder = {elm|")
    (cat packages/url/Url.Builder.elm)
    (echo "|elm}\n\nlet url_parser = {elm|")
    (cat packages/url/Url.Parser.elm)
    (echo "|elm}\n\nlet url_parser_internal = {elm|")
    (cat packages/url/Url.Parser.Internal.elm)
    (echo "|elm}\n\nlet url_parser_query = {elm|")
    (cat packages/url/Url.Parser.Query.elm)
    (echo "|elm}\n\nlet tuple = {elm|")
    (cat packages/core/Tuple.elm)
    (echo "|elm}\n\nlet virtual_dom = {elm|")
    (cat packages/virtual-dom/VirtualDom.elm)
    (echo "|elm}\n")))))

(library
 (name prelude)
 (libraries canonical)
 (preprocess
  (pps ppx_jane)))
