import * as Dartea_browser from "./Dartea_browser.mjs";
import * as Url from "./Url.mjs";
const Internal = _0 => ({ TAG: "Internal", _0: _0 });
const External = _0 => ({ TAG: "External", _0: _0 });
const sandbox = Dartea_browser.$$Browser$sandbox;
const element = Dartea_browser.$$Browser$element;
const document = Dartea_browser.$$Browser$document;
const application = impl => Dartea_browser.$$Browser$application(Url.fromString, impl);
const Document = ($a0, $a1) => ({ title: $a0, body: $a1 });
export { Document, External, Internal, application, document, element, sandbox };
