(env
 (_
  (flags
   (-w -40 -w +26 -warn-error +8))))

(rule
 (target licence_text.ml)
 (deps ../NOTICE)
 (action
  (with-stdout-to
   licence_text.ml
   (progn
    (echo "let notice = {notice|")
    (cat ../NOTICE)
    (echo "|notice}\n")))))

(library
 (name dartea)
 (libraries
  base
  parse
  prelude
  primitives
  infer
  typed
  interface
  canonicalization
  ast
  project
  data
  after_typed
  codegen_js
  reporting)
 (flags
  (-w -40 -w +26))
 (preprocess
  (pps ppx_jane ppx_deriving.show ppx_deriving.make)))
