(rule
 (target runtime_source.ml)
 (deps dartea_runtime.js dartea_browser.js)
 (action
  (with-stdout-to
   runtime_source.ml
   (progn
    (echo "let dartea_runtime = {js|")
    (cat dartea_runtime.js)
    (echo "|js}\n\nlet dartea_browser = {js|")
    (cat dartea_browser.js)
    (echo "|js}\n")))))

(library
 (name codegen_js)
 (libraries base ast optimized data typed after_typed)
 (preprocess
  (pps ppx_jane ppx_deriving.show)))
